version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - backend/.env
    ports:
      - "8000:8000"
    networks:
      - mynetwork

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        REACT_APP_API_URL: "http://localhost:8000"
        REACT_APP_WEBSOCKET_URL: "ws://127.0.0.1:8000"
    ports:
      - "3000:80"
    networks:
      - mynetwork

volumes:
  postgres_data:  # Можете удалить, если больше не нужен

networks:
  mynetwork:
