# Generated by Django 5.1.2 on 2024-10-27 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=100)),
                ('cat_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('cat_weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cat_age', models.IntegerField(help_text='Age of the cat in years')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('stay_type', models.CharField(choices=[('pickup', 'Pickup by Catnanny'), ('visit', 'Visit at Owner’s')], help_text="Indicates if the cat should be picked up or visited at owner's place.", max_length=20)),
                ('message', models.TextField(blank=True, help_text='Message from the owner to the catnanny', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('catnanny', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_received', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_made', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
