# Generated by Django 5.1.2 on 2024-11-01 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
        ('users', '__first__'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='catnanny',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to='users.profile'),
        ),
        migrations.AlterField(
            model_name='review',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_made', to='users.profile'),
        ),
    ]
