# Generated by Django 5.1.2 on 2024-10-19 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('bio', models.TextField(max_length=500)),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('has_pets', models.BooleanField(default=False)),
                ('has_children_under_10', models.BooleanField(default=False)),
                ('work_at_my_house', models.BooleanField(default=False)),
                ('works_at_client_site', models.BooleanField(default=False)),
                ('photo_url', models.URLField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
