# Generated by Django 5.1.2 on 2024-10-26 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_work_at_my_house_profile_pickup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_catnanny',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_pet_owner',
            field=models.BooleanField(default=False),
        ),
    ]
